"""
GitHub PR commenter for CouncilAI (Hours 9-14, Person B).

Formats the verdict as a markdown card and posts it as a PR review via
github_client.post_pr_review(). Attempts inline line-level comments from
citations; per the plan's Hour 14 sync note, GitHub rejects (422) an
inline comment whose line isn't inside a changed hunk, so every inline
comment is wrapped individually and falls back to being folded into the
review body instead of failing the whole post.
"""

import logging
from typing import Any, Dict, List, Optional

from sqlalchemy.orm import Session

from github_client import post_pr_review
from models import Citation, Opinion, Review, Verdict

logger = logging.getLogger(__name__)

_DECISION_EMOJI = {
    "APPROVE": "🟢",
    "REJECT": "🔴",
    "WARN": "🟡",
    "REQUEST_CHANGES": "🟠",
    "ESCALATE_TO_HUMAN": "🟣",
}

_GITHUB_EVENT_FOR_DECISION = {
    "APPROVE": "APPROVE",
    "REJECT": "REQUEST_CHANGES",
    "REQUEST_CHANGES": "REQUEST_CHANGES",
    "WARN": "COMMENT",
    "ESCALATE_TO_HUMAN": "COMMENT",
}


def build_markdown_card(
    review: Review,
    opinions: List[Opinion],
    verdict: Verdict,
    precedents: Optional[List[Dict[str, Any]]] = None,
    dashboard_url: Optional[str] = None,
) -> str:
    """Builds the '## CouncilAI Verdict' markdown card from the plan's template."""
    emoji = _DECISION_EMOJI.get(verdict.final_decision.value, "⚪")

    lines = [f"## CouncilAI Verdict: {emoji} {verdict.final_decision.value}", ""]

    if verdict.escalate_to_human:
        lines.append(f"**⚠️ Escalated to human review:** {verdict.escalation_reason}")
        lines.append("")

    lines.append(f"**Change type:** `{review.change_type.value if review.change_type else 'unknown'}` "
                 f"(confidence {review.change_confidence or 0:.2f})")
    lines.append(f"**Weighted score:** {verdict.weighted_score:.3f} "
                 f"&nbsp;|&nbsp; **Final confidence:** {verdict.final_confidence:.2f}")
    lines.append("")

    lines.append("| Agent | Decision | Confidence | Weight | Key concern |")
    lines.append("|---|---|---|---|---|")
    for op in opinions:
        key_concern = (op.reasoning_text or "").strip().replace("\n", " ")
        if len(key_concern) > 100:
            key_concern = key_concern[:97] + "..."
        lines.append(
            f"| {op.agent_name} | {op.decision.value} | "
            f"{op.confidence:.2f} → {op.adjusted_confidence or op.confidence:.2f} | "
            f"{op.relevance_weight or 1.0:.1f}x | {key_concern or '—'} |"
        )
    lines.append("")

    if precedents:
        lines.append(f"**Precedent engine:** found {len(precedents)} similar past decision(s), "
                     f"top match {precedents[0]['similarity']:.2f} similarity "
                     f"({precedents[0]['decision']}).")
        lines.append("")

    if dashboard_url:
        lines.append(f"[View full reasoning trace]({dashboard_url})")

    lines.append("")
    lines.append("<sub>Generated by CouncilAI — evidence-weighted multi-agent review, not majority vote.</sub>")

    return "\n".join(lines)


def _build_inline_comments(opinions: List[Opinion], db: Session, valid_line_ranges: Dict[str, set]) -> List[Dict[str, Any]]:
    """
    Turns citations into GitHub inline review comments, only when the
    cited line falls within valid_line_ranges (i.e. an actually-changed
    line for that file) — otherwise GitHub returns 422. Callers should
    still send anything dropped here via the review body instead.
    """
    comments = []
    for op in opinions:
        citations = db.query(Citation).filter(Citation.opinion_id == op.id).all()
        for c in citations:
            valid_lines = valid_line_ranges.get(c.file_path, set())
            if c.line_end not in valid_lines and c.line_start not in valid_lines:
                logger.info(f"Skipping inline comment for {c.file_path}:{c.line_end} — not in a changed hunk")
                continue
            body = f"**{op.agent_name}** ({op.decision.value}): {c.description or ''}".strip()
            if c.snippet:
                body += f"\n```\n{c.snippet}\n```"
            comments.append({"path": c.file_path, "line": c.line_end, "body": body})
    return comments


async def post_verdict_to_github(
    db: Session,
    review: Review,
    verdict: Verdict,
    valid_line_ranges: Optional[Dict[str, set]] = None,
    precedents: Optional[List[Dict[str, Any]]] = None,
    dashboard_url: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Posts the CouncilAI verdict as a PR review. Falls back to a
    body-only (no inline comments) review if the inline-comment POST
    fails for any reason — a working file-level comment beats a failed
    post, per the plan's explicit guidance.
    """
    opinions = db.query(Opinion).filter(Opinion.review_id == review.id).all()
    owner, repo_name = review.repo.split("/", 1)
    body = build_markdown_card(review, opinions, verdict, precedents, dashboard_url)
    event = _GITHUB_EVENT_FOR_DECISION.get(verdict.final_decision.value, "COMMENT")

    inline_comments = []
    if valid_line_ranges:
        inline_comments = _build_inline_comments(opinions, db, valid_line_ranges)

    result = await post_pr_review(
        owner=owner, repo=repo_name, pr_number=review.pr_number,
        commit_id=review.commit_sha, body_markdown=body, event=event,
        inline_comments=inline_comments or None,
    )

    if result is None and inline_comments:
        logger.warning("Review post with inline comments failed — retrying as a body-only comment")
        result = await post_pr_review(
            owner=owner, repo=repo_name, pr_number=review.pr_number,
            commit_id=review.commit_sha, body_markdown=body, event=event,
            inline_comments=None,
        )

    if result is not None:
        verdict.github_comment_posted = True
        verdict.github_comment_url = result.get("html_url")
        db.commit()

    return {"posted": result is not None, "response": result, "markdown": body}
